const FIRST_NAME = "Fellipe";

console.log(FIRST_NAME);

// const FIRST_NAME;





// NÃO PODE SER RE-DECLARADD
// NÃO PODE SER RE-ATRIBUIDO
// NÃO FAZ HOISTING
// ESCOPO DE BLOCO
// DECLARAR SEMPRE EM SNAKE_UPPER_CASE